spring:
  application:
    name: 'user-service'
    version: @project.version@

  # Spring Data Config
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  # ORM Config
  jpa:
    properties:
      hibernate:
        dialect: ${SQL_DIALECT}

    hibernate:
      ddl-auto: update

    show-sql: true

# Swagger UI Config
springdoc:
  swagger-ui:
    path: '${spring.application.name}/swagger-ui.html'

# Server Config
server:
  port: 8080
  servlet:
    context-path: '/${spring.application.name}'